# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxGithubSearch' do
  use_frameworks!
  pod "RxSwift"
  pod "RxCocoa"
  pod 'ReactorKit'
  pod 'Alamofire'

  # Pods for RxGithubSearch
  
  target 'RxGithubSearchTests' do
    inherit! :search_paths
    pod 'Quick'
  end
 
end
